# Generated by Django 2.2.4 on 2023-11-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='django_app.User'),
            preserve_default=False,
        ),
    ]
